"""Initial schema migration

Revision ID: 82e0ee282789
Revises: 
Create Date: 2026-05-26 21:17:22.614908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82e0ee282789'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('business_processes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('module', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('criticality_level', sa.String(length=50), nullable=False),
    sa.Column('sla_impact', sa.Boolean(), nullable=False),
    sa.Column('revenue_impact', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['business_processes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_processes_module'), 'business_processes', ['module'], unique=False)
    op.create_index(op.f('ix_business_processes_name'), 'business_processes', ['name'], unique=False)
    op.create_index(op.f('ix_business_processes_tenant_id'), 'business_processes', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('go_nogo_status', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releases_name'), 'releases', ['name'], unique=False)
    op.create_index(op.f('ix_releases_status'), 'releases', ['status'], unique=False)
    op.create_index(op.f('ix_releases_tenant_id'), 'releases', ['tenant_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preconditions', sa.Text(), nullable=True),
    sa.Column('expected_results', sa.Text(), nullable=True),
    sa.Column('format_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('criticality', sa.String(length=50), nullable=False),
    sa.Column('type_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('automation_flag', sa.String(length=50), nullable=False),
    sa.Column('business_process_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('criticality_score', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_process_id'], ['business_processes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_business_process_id'), 'test_cases', ['business_process_id'], unique=False)
    op.create_index(op.f('ix_test_cases_created_at'), 'test_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_cases_criticality'), 'test_cases', ['criticality'], unique=False)
    op.create_index(op.f('ix_test_cases_status'), 'test_cases', ['status'], unique=False)
    op.create_index(op.f('ix_test_cases_tenant_id'), 'test_cases', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_test_cases_title'), 'test_cases', ['title'], unique=False)
    op.create_table('change_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('update_set_ref', sa.String(length=255), nullable=True),
    sa.Column('component_count', sa.Integer(), nullable=False),
    sa.Column('analysis_status', sa.String(length=50), nullable=False),
    sa.Column('impact_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_sets_analysis_status'), 'change_sets', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_change_sets_release_id'), 'change_sets', ['release_id'], unique=False)
    op.create_index(op.f('ix_change_sets_tenant_id'), 'change_sets', ['tenant_id'], unique=False)
    op.create_table('regression_suites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regression_suites_release_id'), 'regression_suites', ['release_id'], unique=False)
    op.create_index(op.f('ix_regression_suites_status'), 'regression_suites', ['status'], unique=False)
    op.create_index(op.f('ix_regression_suites_tenant_id'), 'regression_suites', ['tenant_id'], unique=False)
    op.create_table('change_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_set_id', sa.UUID(), nullable=False),
    sa.Column('component_type', sa.String(length=100), nullable=False),
    sa.Column('component_name', sa.String(length=500), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('raw_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_set_id'], ['change_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_components_change_set_id'), 'change_components', ['change_set_id'], unique=False)
    op.create_index(op.f('ix_change_components_component_type'), 'change_components', ['component_type'], unique=False)
    op.create_table('execution_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('suite_id', sa.UUID(), nullable=True),
    sa.Column('release_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('executed_by', sa.UUID(), nullable=True),
    sa.Column('environment', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('defects_found', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['regression_suites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_history_release_id'), 'execution_history', ['release_id'], unique=False)
    op.create_index(op.f('ix_execution_history_result'), 'execution_history', ['result'], unique=False)
    op.create_index(op.f('ix_execution_history_suite_id'), 'execution_history', ['suite_id'], unique=False)
    op.create_index(op.f('ix_execution_history_tenant_id'), 'execution_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_execution_history_test_case_id'), 'execution_history', ['test_case_id'], unique=False)
    op.create_table('suite_test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suite_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('inclusion_reason', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('execution_status', sa.String(length=50), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['regression_suites.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suite_test_cases_suite_id'), 'suite_test_cases', ['suite_id'], unique=False)
    op.create_index(op.f('ix_suite_test_cases_test_case_id'), 'suite_test_cases', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suite_test_cases_test_case_id'), table_name='suite_test_cases')
    op.drop_index(op.f('ix_suite_test_cases_suite_id'), table_name='suite_test_cases')
    op.drop_table('suite_test_cases')
    op.drop_index(op.f('ix_execution_history_test_case_id'), table_name='execution_history')
    op.drop_index(op.f('ix_execution_history_tenant_id'), table_name='execution_history')
    op.drop_index(op.f('ix_execution_history_suite_id'), table_name='execution_history')
    op.drop_index(op.f('ix_execution_history_result'), table_name='execution_history')
    op.drop_index(op.f('ix_execution_history_release_id'), table_name='execution_history')
    op.drop_table('execution_history')
    op.drop_index(op.f('ix_change_components_component_type'), table_name='change_components')
    op.drop_index(op.f('ix_change_components_change_set_id'), table_name='change_components')
    op.drop_table('change_components')
    op.drop_index(op.f('ix_regression_suites_tenant_id'), table_name='regression_suites')
    op.drop_index(op.f('ix_regression_suites_status'), table_name='regression_suites')
    op.drop_index(op.f('ix_regression_suites_release_id'), table_name='regression_suites')
    op.drop_table('regression_suites')
    op.drop_index(op.f('ix_change_sets_tenant_id'), table_name='change_sets')
    op.drop_index(op.f('ix_change_sets_release_id'), table_name='change_sets')
    op.drop_index(op.f('ix_change_sets_analysis_status'), table_name='change_sets')
    op.drop_table('change_sets')
    op.drop_index(op.f('ix_test_cases_title'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_tenant_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_status'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_criticality'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_created_at'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_business_process_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_releases_tenant_id'), table_name='releases')
    op.drop_index(op.f('ix_releases_status'), table_name='releases')
    op.drop_index(op.f('ix_releases_name'), table_name='releases')
    op.drop_table('releases')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_business_processes_tenant_id'), table_name='business_processes')
    op.drop_index(op.f('ix_business_processes_name'), table_name='business_processes')
    op.drop_index(op.f('ix_business_processes_module'), table_name='business_processes')
    op.drop_table('business_processes')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
